User signup
Mate2xo/crowddjango pull request #2
Opened 2022-10-12 16:46 UTC by Mate2xo

J'ai juste renommé l'app `profiles` en `account` pour y regrouper les vues de login/signup/profil.
L'exercice m'a montré que c'est pas évident à faire, et je n'ai pas trouvé de solution propre pour que les migrations se fassent correctement en prod. Vu que ce n'est pas pushé, je n'ai pas creusé plus pour l'instant

J'ai essayé de passer par un form object pour gérer l'inscription utilisateur, mais j'aurais aimé pourvoir gérer les "nested_attributes" via ce form object pour pouvoir assigner le profil physique/moral sélectionné. Il y a peut-être moyen, mais j'ai fait ça dans le controller(=la `view` quoi) pour l'instant histoire de passer à la suite. Je serais curieux de savoir comment injecter des genre de transactions DRY dans ces `view`

2022-10-13 13:13 UTC, Kernael requested changes

2022-10-13 13:16 UTC, Kernael commented
@Mate2xo En effet ça serait pas mal de voir comment fonctionnent les nested attributes / nested forms avec Django. Ça à pas l'air évident à trouver, après une toute petite recherche Google, mais il devrait y avoir moyen de s'en sortir

2022-10-14 09:52 UTC, Mate2xo commented on accounts/admin.py
> +admin.site.register(User, UserAdmin)
ça vient direct de la [doc](https://docs.djangoproject.com/en/4.1/topics/auth/customizing/#extending-the-existing-user-model)
Honnêtement ça me semble un peu alambiqué. Ce que je comprend, c'est que pour pouvoir render les nested resources (=Inline), il faut configurer la partie Admin du `User`. Pour cela, on sous-classe `BaseUserAdmin` pour lui affecter les inline, puis on re-register `User` avec ces nouvelles options contenue dans cette nouvelle sous-classe.

2022-10-14 09:53 UTC, Mate2xo commented on accounts/templates/registration/login.html
> +{% endif %}
Yes j'aimerais bien faire du I18n, mais je n'ai pas encore lu cette partie de la doc

2022-10-14 09:55 UTC, Mate2xo commented on accounts/templates/registration/login.html
> +{% endblock %}
4 espaces c'est la convention pour Python je crois. Je n'ai rien vu pour les templates Django ; je remets à 2.

2022-10-14 10:23 UTC, Kernael commented on accounts/templates/registration/login.html
> +{% endblock %}
En effet Python c'est 4, selon PEP-8 ! Du coup vaut peut-être mieux garder 4 pour le template aussi

2022-10-14 10:24 UTC, Kernael commented on accounts/admin.py
> +admin.site.register(User, UserAdmin)
chelax 🤷
✅

2022-10-17 13:54 UTC, Mate2xo commented
Il me manque à tester le I18n pour les vue JS, je ferais ça quand je commencerais à ajouter des .js

2022-10-18 09:04 UTC, Kernael commented on accounts/forms.py
> +    profile_type = forms.ChoiceField(choices = [('Legal', 'Personne morale'), ('Natural', 'Personne physique')])
À voir comment faire de l'i18n aussi là pour les prochaines PR

2022-10-18 09:05 UTC, Kernael approved these changes

2022-10-18 09:05 UTC, merged