Create Subscription model, associate it with Fund and User Profile
Mate2xo/crowddjango pull request #4
Opened 2022-10-13 14:51 UTC by Mate2xo

[Ticket](https://trello.com/c/nSYy7XpK/9-model-souscription)
Pour l'instant, j'ai fait un simple model `Subscription` qui est associé soit à un `LegalProfile`, soit à un `NaturalProfile`. Les deux sont optionnels, mais l'un d'entre eux doit être choisi, et c'est validé par `.clean()`. Il est aussi associé à un `Fund`.
Ces assoc sont en ManyToOne

2022-10-14 08:22 UTC, Kernael requested changes

2022-10-14 08:22 UTC, Kernael commented on investments/models.py
> +    natural_profile = models.ForeignKey(NaturalProfile, on_delete=models.PROTECT, null=True, blank=True)
Le model Souscription devrait avoir une seul clé étrangère pour son Profil lié. Une seule table pour les Profils devrait suffir non ?

2022-10-14 09:59 UTC, Mate2xo commented on investments/models.py
> +    natural_profile = models.ForeignKey(NaturalProfile, on_delete=models.PROTECT, null=True, blank=True)
Oui c'est vrai. Je n'ai pas vu de moyen de faire de STI comme dans Rails, peut-être suffit-il de juste faire des sous-classes ? Par contre on peut faire de la MTI (multi) :thinking:

2022-10-14 10:21 UTC, Kernael commented on investments/models.py
> +    natural_profile = models.ForeignKey(NaturalProfile, on_delete=models.PROTECT, null=True, blank=True)
🤯 What
Je vais me renseigner là-dessus 👀

2022-10-14 12:32 UTC, Mate2xo commented on investments/models.py
> +    natural_profile = models.ForeignKey(NaturalProfile, on_delete=models.PROTECT, null=True, blank=True)
Je suis tombé sur un newsgroup de 2014 où il était discuté qu'ils ne voulait pas supporter le STI dans le core de Django. Il faudrait pour ça utiliser des packages tiers. Je n'en sais pas plus pour l'instant

2022-10-14 13:57 UTC, Kernael commented on investments/models.py
> +    natural_profile = models.ForeignKey(NaturalProfile, on_delete=models.PROTECT, null=True, blank=True)
En attendant yes tu peux faire de sous-classes simplement !

2022-10-19 16:53 UTC, Mate2xo commented on investments/models.py
> +    natural_profile = models.ForeignKey(NaturalProfile, on_delete=models.PROTECT, null=True, blank=True)
Je suis parti pour utiliser le package [django-polymorphic](https://github.com/django-polymorphic/django-polymorphic/tree/5111fb070e4e0b0153e816d163871f2039ca2ae2) car c'est un package apparemment connu, et il utlise la solution que je voulais tout en optimisant les requêtes SQL ; donc c'était l'occase de s'entrainer dessus.
Cet article recense bien les possibilités d'héritages de modèle : https://github.com/django-polymorphic/django-polymorphic/tree/5111fb070e4e0b0153e816d163871f2039ca2ae2

Ici j'ai donc utilisé le MTI tout en associant les profils/sous-profils à des `ContentType` pour que les différents profils `Legal`/`Natural` se comportent plus comme une entité unique. On a alors les champs communs dans la table `accounts_profile`, et les champs spécifique à un sous-type dans les tables `accounts_legal` et `accounts_natural`. Les sous-tables ont des références directes à leur parent (`Profile`) via une foreign key (`OneToOne`) qui leur sert aussi de primary key.
J'ai profité de l'occasion pour m'entraîner à faire des migrations, vu que la structure est très simple. J'ai donc essayé de migrer les profils existants vers la nouvelle structure, et c'était pas évident. C'est pour ça qu'il y a autant d'étapes de migration : j'ai d'abord ajouté les attributs sur un nouveau modèle parent permettant de migrer la data, ensuite migré la data, puis finalement évolué la structure pour que les profils existants deviennent enfants.

Si c'est pas clair on peut se call hein. J'ai mis du temps à capter ce truc

2022-10-20 07:15 UTC, Kernael approved these changes

2022-10-20 07:15 UTC, Kernael commented
Stylé !

2022-10-20 07:15 UTC, merged